export const scenarioDefinitions = [
  { name: "empty-session-layout", family: "session" },
  { name: "mobile-layout", family: "mobile" },
  { name: "session-routing", family: "session" },
  { name: "sessions-page", family: "session" },
  { name: "streaming-responsiveness", family: "transcript" },
  { name: "queued-follow-up", family: "transcript" },
  { name: "transcript-scroll-stability", family: "transcript" },
  { name: "transcript-text-selection", family: "transcript" },
  { name: "session-metadata", family: "session" },
  { name: "inspector-preview", family: "transcript" },
  { name: "slash-commands", family: "slash-command" },
  { name: "new-session-command", family: "slash-command" },
  { name: "configured-extension-smoke", family: "slash-command" },
  { name: "bash-commands", family: "slash-command" },
  { name: "question-answer", family: "session" },
  { name: "tree-fork-navigation", family: "session" },
  { name: "reconnect-controller", family: "lifecycle" },
  { name: "controller-handoff-edges", family: "lifecycle" },
  { name: "reconnect-draft", family: "lifecycle" },
  { name: "backend-restart", family: "lifecycle" },
  { name: "connection-disconnected", family: "lifecycle", includeInAll: false },
  { name: "narrow-tool-stream", family: "transcript" },
  { name: "tool-grouping", family: "transcript" },
  { name: "bash-tool-card", family: "transcript" },
  { name: "tool-image-heavy-transcript", family: "transcript" },
  { name: "subagent-card", family: "transcript" },
  { name: "subagent-card-reconnect", family: "transcript" },
  { name: "mobile-long-transcript-controls", family: "mobile" },
  { name: "mobile-image-stream-stability", family: "mobile" },
  { name: "file-autocomplete", family: "slash-command" },
  { name: "image-attachments", family: "artifact" },
  { name: "image-paste-attachments", family: "artifact" },
  { name: "image-artifact-drop-upload", family: "artifact" },
  { name: "image-artifact-paths", family: "artifact" },
  { name: "repeated-image-artifact-paths", family: "artifact" },
  { name: "artifact-path-formats", family: "artifact" },
  { name: "remote-image-artifact-paths", family: "artifact" },
  { name: "remote-image-artifact-upload", family: "artifact" },
  { name: "missing-remote-image-artifact", family: "artifact" },
  { name: "model-thinking", family: "transcript" },
  { name: "context-usage", family: "transcript" },
  { name: "themes", family: "visual" },
  { name: "theme-gallery", family: "visual" },
] as const;

export type ScenarioDefinition = typeof scenarioDefinitions[number];
export type RegisteredHarnessScenarioName = ScenarioDefinition["name"];
export type ScenarioFamily = ScenarioDefinition["family"];
