import { dirname } from "node:path";
import { SessionManager, type AgentSessionEvent } from "@mariozechner/pi-coding-agent";
import type { AnswerQuestionPayload, CommandInfo, ModelPolicy, NormalizedAgentEvent, PendingQuestion, SessionRuntimeSettings, SessionSnapshot, WebSession } from "@pi-web-agent/protocol";
import type { BuiltinCommandResult, CreateSessionOptions, ImageContent, PiSessionRunner, SessionHandle } from "./pi-runner.js";

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

type Listener = (event: NormalizedAgentEvent, raw: AgentSessionEvent) => void;
type FakeMessage = { id: string; role: "user" | "assistant"; timestamp: string; content: string | ({ type: "text"; text: string } | ImageContent)[] };

function normalize(event: Record<string, unknown>): NormalizedAgentEvent {
  return { type: String(event.type ?? "event"), time: new Date().toISOString(), data: event };
}

function fakeSettings(modelPolicy: ModelPolicy): SessionRuntimeSettings {
  const availableModels = [
    { id: "fake/fast", provider: "fake", name: "Fake Fast" },
    { id: "fake/slow", provider: "fake", name: "Fake Slow" },
  ].filter((model) => !modelPolicy.allowedModels || modelPolicy.allowedModels.includes(model.id));
  return {
    model: availableModels[0] ?? null,
    availableModels,
    thinkingLevel: modelPolicy.defaultThinkingLevel,
    availableThinkingLevels: modelPolicy.allowedThinkingLevels,
    contextUsage: {
      tokens: 4_200,
      contextWindow: 200_000,
      percent: 2.1,
    },
  };
}

const fakePreviewPng = "iVBORw0KGgoAAAANSUhEUgAAAWgAAACgCAYAAAAhKfa4AAADUElEQVR42u3d0QnCMBiF0W4gFaRQRBDcoDt1GmdxiS7UDeICVaE25m88D+fVC0n4Hm0z3lMCIJ7GIQAINAACDSDQAAg0gEADINAArA50118ByECgAQQaAIEGEGiBBhBoAIEWaACBBkCgAQQaAIEGEGiBBhBoAAQaQKABEGgAgRZoAIEGEGiBBhBoAAQaQKABEGgAgRZoAIEGQKABBBoAgQYQaIEGEGgAgRZoAIEGQKABBBoAgQYQaIEGEGgABBrgfwJ9PJ3fOrTdVz79vn379u3Xui/Q9u3bt19roB2wffv27efZF2j79u3bF2gXZN++ffsCbd++ffsCLdD27du3L9AeiH379gVaoO3bt29foF2Qffv27Qu0ffv27Qu0C7Jv3759gfZA7Nu3L9BBA/2YJ4DsBFqgAYEWaACBFmhAoAUaQKAD/WH/0kFehhvAaktd8UUVgQYEWqABBFqgAYEWaIEGBFqgAYEWaIEGBFqgAQRaoAGBFmgAgRZoQKAFWqABgRZoQKAFWqABgRZoAIEWaECgSwc62h/2e2DA1oH2RRWBBgRaoAEEWqABgRZogQYEWqABgRZogQYEWqABBFqgAYEWaACBFmhAoAVaoAGBFmhAoAVaoAGBFmgAgRZoQKBLB9of9gO1B9oXVQQaEGiBBhBogQYEWqAFGhBogQYEWqAFGhBogQYQaIEGBFqgAQRaoAGBFmiBBgRaoAGBFmiBBgRaoAEEWqABgS4daH/YD9QeaF9UEWhAoAUaQKAFGhBogRZoQKCDBxpgawIt0IBACzSAQAs0INACDSDQgQL9iwOyb9++fYF2Qfbt27cv0Pbt27cv0C7Ivn379gXavn379gVaoO3bt29/H4F2wPbt27fviyoeiH379gVaoO3bt29foF2Qffv27Qu0ffv27Qu0C7Jv3759gfZA7Nu3L9ACbd++ffsC7YLs27dvX6Dt27dvX6BdkH379u0LtH379u0LtEDbt2/fvkB7IPbt2xdogbZv3759gXZB9u3bt5830A7Yvn379n1RxQOxb9++QAu0ffv27Qu0C7Jv3759gbZv3759gXZB9u3bty/QHoh9+/YFWqDt27dvf2+BBqAMgQYQaAAEGkCgARBoAIEGQKABeOkJWSAfL9rB/N8AAAAASUVORK5CYII=";

function responseFor(text: string): string {
  const includesImage = /(?:image|screenshot|picture)/i.test(text);
  const includesArtifactPath = /(?:artifact path|screenshot path|local image path)/i.test(text);
  const includesArtifactFormatVariants = /(?:artifact format variants|inline fenced long artifact)/i.test(text);
  const requestedLength = /(?:long|stream|perf|performance)/i.test(text) ? 18000 : includesImage ? 3200 : 1400;
  const imageBlock = includesArtifactFormatVariants
    ? "\nRelevant screenshot artifact format variants:\n\nInline code: `screenshots/inline.png`\n\nFenced code:\n\n```text\nscreenshots/fenced.png\n```\n\nLong generated path: `test-results/ui-harness/sample-run/final.png`\n\nAll three workspace-relative paths should render safe local image previews.\n"
    : includesArtifactPath
      ? "\nRelevant screenshot artifacts:\n\n- `screenshots/fixture.png`\n- screenshots/fixture.png\n\nThe UI should render a safe local image preview for that workspace-relative path.\n"
      : includesImage
        ? `\n![Fake UI validation preview](data:image/png;base64,${fakePreviewPng})\n\nThe image above is an inline base64 PNG rendered from assistant Markdown.\n`
        : "";
  const seed = [
    "# Synthetic streaming response",
    "",
    "This response is generated by the pi-web fake agent runner for browser automation. It intentionally streams a lot of text so the UI can be tested without calling a real model.",
    imageBlock,
    "",
    "The stream deliberately includes Markdown that arrives mid-token, partial code fences, event bursts, and delayed tool updates so browser automation can catch UI regressions that a perfectly regular fake stream would miss.",
    "",
    "```ts",
    "export function example(value: string) {",
    "  return value.toUpperCase();",
    "}",
    "```",
    "",
  ].join("\n");
  const paragraph = [
    "The quick brown fox checks whether prompt typing, inspector controls, transcript selection, and auto-scroll remain responsive while the assistant message grows.",
    "Every few sentences the fake runner crosses **Markdown emphasis**, `inline code`, list boundaries, and fenced code blocks in awkwardly sized chunks.",
    "\n\n- streamed bullet one\n- streamed bullet two with a [local link](./README.md)\n\n```ts\nconst partialFence = true;\nconsole.log({ partialFence });\n```\n\n",
  ].join(" ");
  return (seed + paragraph.repeat(Math.ceil(requestedLength / paragraph.length))).slice(0, requestedLength);
}

function streamChunkSize(index: number): number {
  const sizes = [34, 147, 9, 216, 61, 88, 19, 132, 44, 305, 72, 118];
  return sizes[index % sizes.length] ?? 90;
}

function streamDelayMs(index: number): number {
  // Deterministic uneven cadence: short bursts, normal token cadence, and occasional stalls.
  if (index % 17 === 0 || index % 17 === 1 || index % 17 === 2) return 0;
  if (index % 29 === 0) return 95;
  if (index % 11 === 0) return 42;
  const delays = [8, 14, 23, 6, 31, 18, 12, 27];
  return delays[index % delays.length] ?? 16;
}

class FakeSessionHandle implements SessionHandle {
  readonly session: any;
  private readonly sessionManager: SessionManager;
  private readonly listeners = new Set<Listener>();
  private readonly messages: FakeMessage[] = [];
  private aborted = false;
  private currentModel = "fake/fast";
  private currentThinking: string;
  private steeringQueue: Array<{ text: string; images: ImageContent[] | undefined }> = [];
  private followUpQueue: Array<{ text: string; images: ImageContent[] | undefined }> = [];
  private pendingQuestion: PendingQuestion | null = null;
  private questionResolver: ((answer: Required<Pick<AnswerQuestionPayload, "cancelled">> & Omit<AnswerQuestionPayload, "cancelled">) => void) | null = null;
  private readonly questionListeners = new Set<(question: PendingQuestion | null) => void>();

  constructor(
    readonly id: string,
    readonly cwd: string,
    readonly sessionFile: string,
    private readonly modelPolicy: ModelPolicy,
  ) {
    this.currentThinking = modelPolicy.defaultThinkingLevel;
    this.sessionManager = SessionManager.open(sessionFile, dirname(sessionFile), cwd);
    this.session = {
      isStreaming: false,
      state: { messages: this.messages },
      sessionManager: this.sessionManager,
      navigateTree: (entryId: string) => this.navigateTree(entryId),
    };
    this.restoreMessagesFromSession();
  }

  async prompt(text: string, images?: ImageContent[]): Promise<void> {
    const now = new Date().toISOString();
    const userContent = images?.length ? [{ type: "text" as const, text }, ...images] : text;
    const user: FakeMessage = { id: crypto.randomUUID(), role: "user", timestamp: now, content: userContent };
    this.messages.push(user);
    this.sessionManager.appendMessage({ role: "user", content: userContent } as never);
    this.emit({ type: "message_end", message: user });

    const shouldAskQuestion = /(?:question-answer|ask_question|ask question|clarif)/i.test(text);
    const shouldRunTool = /tool/i.test(text) && !shouldAskQuestion;
    const toolRunCount = /(?:multiple|many|group)\s+tools/i.test(text) ? 4 : 1;

    this.aborted = false;
    this.session.isStreaming = true;
    this.emit({ type: "agent_start" });

    if (shouldAskQuestion) {
      await this.emitFakeQuestionRun(/cancel/i.test(text));
      this.session.isStreaming = false;
      this.steeringQueue = [];
      this.followUpQueue = [];
      this.emit({ type: "agent_end" });
      this.emitQueueUpdate();
      return;
    }

    const assistant: FakeMessage = { id: crypto.randomUUID(), role: "assistant", timestamp: new Date().toISOString(), content: "" };
    this.messages.push(assistant);
    this.emit({ type: "message_start", message: assistant });

    const full = responseFor(text);
    const toolAtOffset = shouldRunTool ? Math.min(Math.max(450, Math.floor(full.length * 0.22)), full.length - 1) : Infinity;
    let emittedTool = false;
    for (let offset = 0, chunkIndex = 0; offset < full.length && !this.aborted; chunkIndex++) {
      const nextOffset = Math.min(full.length, offset + streamChunkSize(chunkIndex));
      assistant.content = full.slice(0, nextOffset);
      this.emit({ type: "message_update", message: { ...assistant } });
      offset = nextOffset;

      if (!emittedTool && offset >= toolAtOffset) {
        emittedTool = true;
        for (let toolIndex = 0; toolIndex < toolRunCount; toolIndex++) {
          await this.emitFakeToolRun(/(?:long|narrow)/i.test(text), toolIndex + 1);
        }
      }

      const delay = streamDelayMs(chunkIndex);
      if (delay > 0) await sleep(delay);
    }
    if (this.aborted) assistant.content += "\n\n[aborted]";
    else assistant.content = full;
    this.sessionManager.appendMessage({ role: "assistant", content: assistant.content } as never);
    this.emit({ type: "message_end", message: { ...assistant } });
    this.session.isStreaming = false;
    this.steeringQueue = [];
    this.followUpQueue = [];
    this.emit({ type: "agent_end" });
    this.emitQueueUpdate();
  }

  async steer(text: string, images?: ImageContent[]): Promise<void> {
    this.steeringQueue.push({ text, images });
    this.emitQueueUpdate();
  }

  async followUp(text: string, images?: ImageContent[]): Promise<void> {
    this.followUpQueue.push({ text, images });
    this.emitQueueUpdate();
  }

  async cancelQueuedMessage(queue: "steering" | "followUp", index: number, text?: string): Promise<{ steering: string[]; followUp: string[] }> {
    const target = queue === "steering" ? this.steeringQueue : this.followUpQueue;
    if (index >= target.length) throw new Error("Queued message no longer exists.");
    if (text !== undefined && target[index]?.text !== text) throw new Error("Queued message changed before it could be canceled.");
    target.splice(index, 1);
    this.emitQueueUpdate();
    return { steering: this.steeringQueue.map((message) => message.text), followUp: this.followUpQueue.map((message) => message.text) };
  }

  async abort(): Promise<void> {
    this.aborted = true;
    this.cancelPendingQuestion();
  }

  getPendingQuestion(): PendingQuestion | null {
    return this.pendingQuestion;
  }

  answerQuestion(payload: AnswerQuestionPayload): void {
    if (!this.pendingQuestion || payload.questionId !== this.pendingQuestion.id || !this.questionResolver) throw new Error("No matching pending question.");
    const resolver = this.questionResolver;
    this.pendingQuestion = null;
    this.questionResolver = null;
    this.emitQuestionUpdate();
    resolver({
      questionId: payload.questionId,
      answer: payload.cancelled ? undefined : payload.answer,
      selectedIndex: payload.selectedIndex ?? null,
      wasCustom: payload.wasCustom ?? false,
      cancelled: payload.cancelled ?? false,
    });
  }

  subscribeQuestion(listener: (question: PendingQuestion | null) => void): () => void {
    this.questionListeners.add(listener);
    return () => this.questionListeners.delete(listener);
  }

  async setModel(model: string): Promise<void> {
    this.currentModel = model;
  }

  async setThinkingLevel(level: string): Promise<void> {
    this.currentThinking = level;
  }

  setSessionName(_name: string): void {
    // Fake runner keeps the canonical web title in metadata only.
  }

  async getSettings(): Promise<SessionRuntimeSettings> {
    const settings = fakeSettings(this.modelPolicy);
    const tokens = 4_200 + this.messages.reduce((sum, message) => sum + (typeof message.content === "string" ? message.content.length : JSON.stringify(message.content).length), 0) / 4;
    const contextWindow = 200_000;
    return {
      ...settings,
      model: settings.availableModels.find((model) => model.id === this.currentModel) ?? settings.model,
      thinkingLevel: this.currentThinking,
      contextUsage: {
        tokens: Math.round(tokens),
        contextWindow,
        percent: (tokens / contextWindow) * 100,
      },
    };
  }

  getCommands(): CommandInfo[] {
    return [
      { name: "tree", description: "Open the web session tree", source: "builtin" },
      { name: "new", description: "Start a new web session in the same workspace", source: "builtin" },
      { name: "grill-me", description: "Start a one-question-at-a-time codebase interview using ask_question", source: "skill", argumentHint: "[topic or goal]" },
      { name: "session", description: "Show session info", source: "builtin" },
      { name: "reload", description: "Reload fake resources", source: "builtin" },
    ];
  }

  async runBuiltinCommand(text: string): Promise<BuiltinCommandResult> {
    const trimmed = text.trim();
    if (trimmed === "/session") return { handled: true, title: "/session", body: `Fake session ${this.id}\nMessages: ${this.messages.length}` };
    if (trimmed === "/reload") return { handled: true, title: "/reload", body: "Reloaded fake resources." };
    if (trimmed === "/tree") return { handled: true, title: "/tree", body: "Open the Tree tab or wide tree drawer." };
    if (/^\/grill-me(?:\s|$)/.test(trimmed)) {
      const focus = trimmed.replace(/^\/grill-me(?:\s+)?/, "").trim();
      return {
        handled: true,
        title: "/grill-me",
        launchPrompt: [
          "Run the bundled `grill-me` skill for this coding session.",
          focus ? `Operator-provided focus: ${focus}` : "Operator-provided focus: general project/codebase review.",
          "Use the ask_question tool for each question. Ask exactly one concise question at a time and include a recommendation.",
        ].join("\n"),
      };
    }
    return { handled: false };
  }

  subscribe(listener: Listener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  async snapshot(webSession: WebSession): Promise<SessionSnapshot> {
    return {
      session: webSession,
      status: this.session.isStreaming ? "running" : "idle",
      messages: this.messages,
      settings: await this.getSettings(),
      pendingQuestion: this.pendingQuestion,
    };
  }

  dispose(): void {
    this.aborted = true;
    this.cancelPendingQuestion();
    this.listeners.clear();
    this.questionListeners.clear();
  }

  private emit(event: Record<string, unknown>): void {
    const normalized = normalize(event);
    for (const listener of this.listeners) listener(normalized, event as AgentSessionEvent);
  }

  private emitQueueUpdate(): void {
    this.emit({ type: "queue_update", steering: this.steeringQueue.map((message) => message.text), followUp: this.followUpQueue.map((message) => message.text) });
  }

  private emitQuestionUpdate(): void {
    for (const listener of this.questionListeners) listener(this.pendingQuestion);
  }

  private cancelPendingQuestion(): void {
    if (!this.pendingQuestion || !this.questionResolver) return;
    this.answerQuestion({ questionId: this.pendingQuestion.id, cancelled: true, selectedIndex: null, wasCustom: false });
  }

  private restoreMessagesFromSession(): void {
    this.messages.splice(0, this.messages.length);
    for (const entry of this.sessionManager.getBranch()) {
      if (entry.type !== "message") continue;
      const message = entry.message as unknown as Record<string, unknown>;
      const role = message.role === "assistant" ? "assistant" : message.role === "user" ? "user" : null;
      if (!role) continue;
      this.messages.push({
        id: entry.id,
        role,
        timestamp: entry.timestamp,
        content: message.content as FakeMessage["content"],
      });
    }
  }

  private async navigateTree(entryId: string): Promise<{ cancelled: false; editorText?: string }> {
    const entry = this.sessionManager.getEntry(entryId);
    if (!entry) throw new Error(`Entry not found: ${entryId}`);
    this.sessionManager.branch(entryId);
    this.restoreMessagesFromSession();
    const message = entry.type === "message" ? entry.message as unknown as Record<string, unknown> : null;
    const editorText = message?.role === "user" && typeof message.content === "string" ? String(message.content) : undefined;
    return editorText === undefined ? { cancelled: false } : { cancelled: false, editorText };
  }

  private async emitFakeQuestionRun(expectCancel = false): Promise<void> {
    const toolCallId = crypto.randomUUID();
    const args = {
      title: expectCancel ? "Cancel path" : "Today's work",
      question: expectCancel ? "Should this question be cancelled?" : "What are you working on today?",
      recommendation: expectCancel ? "Cancel this prompt to verify the cancellation path." : "Start with the smallest vertical slice that proves the UI lifecycle.",
      options: [
        { label: "New feature", description: "Adding new functionality to the project" },
        { label: "Bug fix", description: "Tracking down and fixing an issue" },
        { label: "Refactoring", description: "Improving existing code structure" },
      ],
      allowCustomAnswer: true,
    };
    this.emit({ type: "tool_execution_start", toolCallId, toolName: "ask_question", args });
    this.pendingQuestion = { id: crypto.randomUUID(), ...args, createdAt: new Date().toISOString() };
    this.emitQuestionUpdate();
    const answer = await new Promise<Required<Pick<AnswerQuestionPayload, "cancelled">> & Omit<AnswerQuestionPayload, "cancelled">>((resolve) => {
      this.questionResolver = resolve;
    });
    const result = answer.cancelled
      ? { content: [{ type: "text", text: "User cancelled the question." }], details: { questionId: answer.questionId, question: args.question, answer: null, selectedIndex: null, wasCustom: false, cancelled: true } }
      : { content: [{ type: "text", text: `${answer.wasCustom ? "User wrote" : `User selected option ${(answer.selectedIndex ?? 0) + 1}`}: ${answer.answer ?? ""}` }], details: { questionId: answer.questionId, question: args.question, answer: answer.answer ?? null, selectedIndex: answer.selectedIndex ?? null, wasCustom: answer.wasCustom ?? false, cancelled: false } };
    this.emit({ type: "tool_execution_end", toolCallId, toolName: "ask_question", result, isError: false });
    const assistant: FakeMessage = { id: crypto.randomUUID(), role: "assistant", timestamp: new Date().toISOString(), content: answer.cancelled ? "Question cancelled; I can rephrase or proceed with assumptions." : `Thanks — I'll proceed with: ${answer.answer}.` };
    this.messages.push(assistant);
    this.sessionManager.appendMessage({ role: "assistant", content: assistant.content } as never);
    this.emit({ type: "message_end", message: assistant });
  }

  private async emitFakeToolRun(longOutput = false, runIndex = 1): Promise<void> {
    const toolCallId = crypto.randomUUID();
    const args = { command: longOutput ? "for i in {1..80}; do echo fake tool line $i; done" : `echo fake tool ${runIndex}` };
    const outputLines = longOutput
      ? Array.from({ length: 80 }, (_, index) => `[server] fake tool line ${String(index + 1).padStart(2, "0")} {\"level\":30,\"msg\":\"synthetic streaming terminal output\"}`).join("\n")
      : `fake tool ${runIndex} output\nstdout: first line\nstderr: delayed diagnostic`;
    this.emit({ type: "tool_execution_start", toolCallId, toolName: "bash", args });
    await sleep(35);
    this.emit({ type: "tool_execution_update", toolCallId, toolName: "bash", args, partialResult: { content: [{ type: "text", text: "running fake tool...\n" }] } });
    // Burst two updates together to exercise tool-card patching under clustered events.
    this.emit({ type: "tool_execution_update", toolCallId, toolName: "bash", args, partialResult: { content: [{ type: "text", text: `running fake tool...\n${longOutput ? outputLines.split("\n").slice(0, 18).join("\n") + "\n" : "stdout: first line\n"}` }] } });
    await sleep(120);
    this.emit({ type: "tool_execution_update", toolCallId, toolName: "bash", args, partialResult: { content: [{ type: "text", text: longOutput ? `running fake tool...\n${outputLines}\n` : "running fake tool...\nstdout: first line\nstderr: delayed diagnostic\n" }] } });
    await sleep(25);
    this.emit({
      type: "tool_execution_end",
      toolCallId,
      toolName: "bash",
      result: {
        content: [{ type: "text", text: outputLines }],
        details: { stdout: `${outputLines}\n`, stderr: longOutput ? "" : "delayed diagnostic\n", exitCode: 0 },
      },
    });
  }
}

export class FakePiSessionRunner implements PiSessionRunner {
  private readonly handles = new Map<string, SessionHandle>();

  constructor(private readonly modelPolicy: ModelPolicy) {}

  async createSession(options: CreateSessionOptions): Promise<SessionHandle> {
    const existing = this.handles.get(options.id);
    if (existing) return existing;
    const handle = new FakeSessionHandle(options.id, options.cwd, options.piSessionFile, this.modelPolicy);
    this.handles.set(options.id, handle);
    return handle;
  }

  getSession(id: string): SessionHandle | undefined {
    return this.handles.get(id);
  }

  async disposeSession(id: string): Promise<void> {
    this.handles.get(id)?.dispose();
    this.handles.delete(id);
  }
}
