import type { AgentSessionEvent } from "@mariozechner/pi-coding-agent";
import type { CommandInfo, ModelPolicy, NormalizedAgentEvent, SessionRuntimeSettings, SessionSnapshot, WebSession } from "@pi-web-agent/protocol";
import type { BuiltinCommandResult, CreateSessionOptions, PiSessionRunner, SessionHandle } from "./pi-runner.js";

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

type Listener = (event: NormalizedAgentEvent, raw: AgentSessionEvent) => void;
type FakeMessage = { id: string; role: "user" | "assistant"; timestamp: string; content: string };

function normalize(event: Record<string, unknown>): NormalizedAgentEvent {
  return { type: String(event.type ?? "event"), time: new Date().toISOString(), data: event };
}

function fakeSettings(modelPolicy: ModelPolicy): SessionRuntimeSettings {
  const availableModels = [
    { id: "fake/fast", provider: "fake", name: "Fake Fast" },
    { id: "fake/slow", provider: "fake", name: "Fake Slow" },
  ].filter((model) => !modelPolicy.allowedModels || modelPolicy.allowedModels.includes(model.id));
  return {
    model: availableModels[0] ?? null,
    availableModels,
    thinkingLevel: modelPolicy.defaultThinkingLevel,
    availableThinkingLevels: modelPolicy.allowedThinkingLevels,
  };
}

function responseFor(text: string): string {
  const requestedLength = /(?:long|stream|perf|performance)/i.test(text) ? 18000 : 1400;
  const seed = [
    "# Synthetic streaming response",
    "",
    "This response is generated by the pi-web fake agent runner for browser automation. It intentionally streams a lot of text so the UI can be tested without calling a real model.",
    "",
    "```ts",
    "export function example(value: string) {",
    "  return value.toUpperCase();",
    "}",
    "```",
    "",
  ].join("\n");
  const paragraph = "The quick brown fox checks whether prompt typing, inspector controls, transcript selection, and auto-scroll remain responsive while the assistant message grows. ";
  return (seed + paragraph.repeat(Math.ceil(requestedLength / paragraph.length))).slice(0, requestedLength);
}

class FakeSessionHandle implements SessionHandle {
  readonly session: any;
  private readonly listeners = new Set<Listener>();
  private readonly messages: FakeMessage[] = [];
  private aborted = false;
  private currentModel = "fake/fast";
  private currentThinking: string;

  constructor(
    readonly id: string,
    readonly cwd: string,
    readonly sessionFile: string,
    private readonly modelPolicy: ModelPolicy,
  ) {
    this.currentThinking = modelPolicy.defaultThinkingLevel;
    this.session = {
      isStreaming: false,
      state: { messages: this.messages },
      sessionManager: undefined,
    };
  }

  async prompt(text: string): Promise<void> {
    const now = new Date().toISOString();
    const user: FakeMessage = { id: crypto.randomUUID(), role: "user", timestamp: now, content: text };
    this.messages.push(user);
    this.emit({ type: "message_end", message: user });

    if (/tool/i.test(text)) await this.emitFakeToolRun();

    this.aborted = false;
    this.session.isStreaming = true;
    this.emit({ type: "agent_start" });

    const assistant: FakeMessage = { id: crypto.randomUUID(), role: "assistant", timestamp: new Date().toISOString(), content: "" };
    this.messages.push(assistant);
    this.emit({ type: "message_start", message: assistant });

    const full = responseFor(text);
    const chunkSize = 90;
    for (let offset = 0; offset < full.length && !this.aborted; offset += chunkSize) {
      assistant.content = full.slice(0, offset + chunkSize);
      this.emit({ type: "message_update", message: { ...assistant } });
      await sleep(16);
    }
    if (this.aborted) assistant.content += "\n\n[aborted]";
    else assistant.content = full;
    this.emit({ type: "message_end", message: { ...assistant } });
    this.session.isStreaming = false;
    this.emit({ type: "agent_end" });
  }

  async steer(text: string): Promise<void> {
    this.emit({ type: "queue_update", steering: [text], followUp: [] });
  }

  async followUp(text: string): Promise<void> {
    this.emit({ type: "queue_update", steering: [], followUp: [text] });
  }

  async abort(): Promise<void> {
    this.aborted = true;
  }

  async setModel(model: string): Promise<void> {
    this.currentModel = model;
  }

  async setThinkingLevel(level: string): Promise<void> {
    this.currentThinking = level;
  }

  async getSettings(): Promise<SessionRuntimeSettings> {
    const settings = fakeSettings(this.modelPolicy);
    return {
      ...settings,
      model: settings.availableModels.find((model) => model.id === this.currentModel) ?? settings.model,
      thinkingLevel: this.currentThinking,
    };
  }

  getCommands(): CommandInfo[] {
    return [
      { name: "tree", description: "Open the web session tree", source: "builtin" },
      { name: "session", description: "Show session info", source: "builtin" },
      { name: "reload", description: "Reload fake resources", source: "builtin" },
    ];
  }

  async runBuiltinCommand(text: string): Promise<BuiltinCommandResult> {
    if (text.trim() === "/session") return { handled: true, title: "/session", body: `Fake session ${this.id}\nMessages: ${this.messages.length}` };
    if (text.trim() === "/reload") return { handled: true, title: "/reload", body: "Reloaded fake resources." };
    if (text.trim() === "/tree") return { handled: true, title: "/tree", body: "Open the Tree tab or wide tree drawer." };
    return { handled: false };
  }

  subscribe(listener: Listener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  async snapshot(webSession: WebSession): Promise<SessionSnapshot> {
    return {
      session: webSession,
      status: this.session.isStreaming ? "running" : "idle",
      messages: this.messages,
      settings: await this.getSettings(),
    };
  }

  dispose(): void {
    this.aborted = true;
    this.listeners.clear();
  }

  private emit(event: Record<string, unknown>): void {
    const normalized = normalize(event);
    for (const listener of this.listeners) listener(normalized, event as AgentSessionEvent);
  }

  private async emitFakeToolRun(): Promise<void> {
    const toolCallId = crypto.randomUUID();
    this.emit({ type: "tool_execution_start", toolCallId, toolName: "bash", args: { command: "echo fake tool" } });
    await sleep(40);
    this.emit({ type: "tool_execution_update", toolCallId, toolName: "bash", args: { command: "echo fake tool" }, partialResult: { content: [{ type: "text", text: "running fake tool..." }] } });
    await sleep(40);
    this.emit({ type: "tool_execution_end", toolCallId, toolName: "bash", result: { content: [{ type: "text", text: "fake tool output" }], details: { stdout: "fake tool output\n", exitCode: 0 } } });
  }
}

export class FakePiSessionRunner implements PiSessionRunner {
  private readonly handles = new Map<string, SessionHandle>();

  constructor(private readonly modelPolicy: ModelPolicy) {}

  async createSession(options: CreateSessionOptions): Promise<SessionHandle> {
    const existing = this.handles.get(options.id);
    if (existing) return existing;
    const handle = new FakeSessionHandle(options.id, options.cwd, options.piSessionFile, this.modelPolicy);
    this.handles.set(options.id, handle);
    return handle;
  }

  getSession(id: string): SessionHandle | undefined {
    return this.handles.get(id);
  }

  async disposeSession(id: string): Promise<void> {
    this.handles.get(id)?.dispose();
    this.handles.delete(id);
  }
}
